### PR TITLE
Plugin for reading websites using Scrapy as base

### PR DESCRIPTION
**Pull request by Boldie**
Scrapy is a nice framework to support web page data extraction with selectors. This is fare more robust an convenient, like the import plugin already provided by gourmet. Furthermore I added a test framework which enables every website parser author to add a bunch of reference data which is known to work for the needed testcases which can be easily rerun to see if the website is still supported.

For the moment only a single Importer website, Essen und Trinken is supported.

### CODE REVIEW

**Comment by Boldie** [comment]
First I have to solve the problem with the testdata, it is copyrighted content. Maybe I have to scramble it or hash it.

**Comment by thinkle** [comment]
Seems like a nice idea.  BeautifulSoup is also a nice framework,  no? Is
there a strong a argument for replacing with Scrapy (in which case we
should reimplement existing plugins) or are you suggesting we maintain both
sides by side?

Also,  haven't read the code yet,  but I'm curious of you used the
PluginPlugin architecture to support new websites being added or whether
you had a different approach.

Tom

**Comment by Boldie** [comment]
BeautifulSoup is also a nice thing, but I already wrote a bunch of web crawlers using scrapy, which has a cool xpath syntax making data extraction very easy. I had trouble to understand the old plugin structure, my opinion was to write a specific plugin for every website I need. So once a plugin works it will always return the correct data without any additional user interaction like the others have. So just add url, and if no error comes up everything is imported as requested.
To ensure the plugin for the site is still working I used a golden sample test strategy with the testdata. The subplugin fills a dict which can be easily used to create a golden sample and verify the fields if they have been extracted correctly without using the database.

**Comment by thinkle** [comment]
Got it -- the thing about the current structure is that you should be able
to add a new parser in 20 lines of code or so -- take a look at the
importers w/ Gourmet for examples. It looks like BeautifulSoup doesn't
support xpath, but it does support CSS-like syntax, which is usually pretty
easy to convert to from xpath (
http://stackoverflow.com/questions/30636801/convert-xpath-to-beautiful-soup
).

One of the goals of the current importer infrastructure is to allow a
person to double-check and to fail nicely. Given the way Gourmet is
distributed, there's no way to be confident we'll be up to date for a given
website unless we build some new distribution network -- often the version
of Gourmet a distro is shipping is 6 months out of date or more, so I think
it's important web importers fall back and allow people to scrape them by
hand, which is the structure currently used (i.e. the code in webimporters
tries to "preparse," but the parsed page gets shown to the user, with the
possibility of fixing the import by hand before it gets pulled into Gourmet.

Your architecture seems like it would be better if people were trying mass
import (e.g. scraping many URLs at once or many recipes from one page) and
you wanted it fully automated, but in my experience that can backfire (we
used to support fully automated web import, but pages often get worse over
time).

Tom

**Comment by Boldie** [comment]
Yes, there is a way to convert it, but for me the syntax is heavy and as started working with Selectors from scrapy it mades extraction so much easy due to the xpath syntax. I found another library having only the Selector part of scraby: Parsel https://github.com/scrapy/parsel unfortunately it is not very widespread and Ubuntu for e.g. starts adding a package from 16.10.

Your goal for the importer infrastructure is good. I know the trouble with not working web importer plugins, but I found (I wrote some 10 or more years ago with the same problem you stated) the newer style of web pages makes it much more stable, because they often use css fields or special tags (for e.g. essen und trinken uses css tags like <span itemprop='recipeYield'>XY</span> which can be easily identified with a single expression in a stable way: "//span[@itemprop='recipeYield']". The update rate may be a problem, because if one item is broken the user has to wait for the next cycle. But I think plugins should really be plugins and not extras for the program. A mechanism to update them independent of the main program would be nice and solve this problem. Then the user can also decide which one to install or not.

I choose this architecture for the following reasons:
* Once the work instead of always work during import (I have imported 50 recipes so far)
* I know how to program and fixing is easy for me.
* No manual rework needed.
* Ensure the plugin is working with the golden sample tests (can be run every week or so in an automated way)

A preview of the imported dataset would be nice, is there a way or an abstraction layer to open up a window and show the recipe the way it will be viewed later? I am not a GTK expert and I already tried to extend something there which was too much work and I gave up. The project is sometimes hard to analyze, very less comments or hints, architecture is quite unclear and python makes it a further step harder because to find out which class instances or what is really needed is to search the calls to the methods or constructors. It was already hard to find out for the epub plugin or the scrapy one to condensate to what is really needed.

**Pull request closed without merging**
