### PR TITLE
Cleanup1

### PR DESCRIPTION
**Pull request by martinp26**
Please consider pulling these smaller clean-ups, bugfixes, and a feature for the epub generator.

### CODE REVIEW

**Comment by saxon-s** [comment]
Thank you for submitting this pull request. I see you are a first time contributor. Welcome to Gourmet!

At this time we are actively migrating Gourmet to Python 3 and Gtk 3 at [kirienko/gourmet](https://github.com/kirienko/gourmet). I'm therefore holding off merging minor PRs into thinkle/gourmet master for now.

A couple requests:
- As requested on the [Contributing Wiki Page](https://github.com/thinkle/gourmet/blob/master/CONTRIBUTING.md) stick to a _one issue = one commit = one pull request_ policy. Split this PR up into three separate PRs.
- As a general rule, don't change the code formatting (i.e. add or remove spaces, new lines, etc). Otherwise it makes it difficult to compare what has changed and if the change is necessary.
- provide a brief description in your PR commit message why the change is necessary.
- If you are fixing a bug please raise an issue ticket and reference the issue # in the PR

Adhering to the above will make the PR review smoother and the acceptance of the PR easier.

Thank you for your support.

**Comment by martinp26** [comment]
Thanks for the feedback.  I will split things up.  Do you have a rough ETA for the Python 3 and Gtk 3 conversions?

Should I rather submit against kirienko/gourmet for the time being?

**Comment by martinp26** [comment]
#998

**Comment by martinp26** [comment]
https://github.com/thinkle/gourmet/pull/999
https://github.com/thinkle/gourmet/pull/1000
https://github.com/thinkle/gourmet/pull/1002

**Pull request closed without merging**
